version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
      # Obtener la contraseña de acceso para ECR y iniciar sesión en Docker
      - LOGIN_PASSWORD=$(aws ecr get-login-password --region $AWS_REGION)
      - echo "$LOGIN_PASSWORD" | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - export KUBECONFIG=$HOME/.kube/config
  build:
    commands:
      - echo Building Docker image...
      - docker build -t ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${AWS_ECR_REPOSITORY_NAME}:latest .
      - echo Pushing Docker image to ECR...
      - docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${AWS_ECR_REPOSITORY_NAME}:latest
  post_build:
    commands:
      # Descargar el archivo deployment.yml desde el repositorio raíz
      - aws s3 cp s3://tfstate-adrian-jimenez/path/deployment.yml deployment.yml
      - echo "Update Kube Config"      
      - aws eks update-kubeconfig --name $EKS_CLUSTER_NAME
      # Aplicar el archivo deployment.yml en el clúster de EKS
      - kubectl apply -f deployment.yml

artifacts:
  files: []
